# Generated by Django 2.2.7 on 2019-11-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('link', models.URLField()),
                ('author', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('pub_date', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('ex_type', models.CharField(choices=[('양도', '양도'), ('대여', '대여'), ('판매', '판매')], default='양도', max_length=10)),
                ('state', models.CharField(choices=[('unavailable', 'unavailable'), ('available', 'available')], default='unavailable', max_length=10)),
                ('exc_method', models.CharField(choices=[('일반거래', '일반거래'), ('안심거래', '안심거래')], default='일반거래', max_length=10)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstore.UserBook')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
