# Generated by Django 2.2.7 on 2019-11-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='book',
        ),
        migrations.AddField(
            model_name='product',
            name='book_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
