# Generated by Django 2.2.7 on 2019-11-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20191130_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exc_method',
            field=models.CharField(choices=[('일반거래', '일반거래'), ('중개거래', '중개거래')], default='일반거래', max_length=10),
        ),
    ]
